### ISSUE TITLE
Volume mounts will not work on Windows

### ISSUE THREAD

**Issue by thebetterjort** [strapi/strapi-docker#14]
I, unfortunately, am trying to develop on a Windows Box.

But the volume mounts will not work as described below.

https://github.com/docker-library/docs/blob/b78d49c9dffe5dd8b3ffd1db338c62b9e1fc3db8/mongo/content.md#where-to-store-data

**Comment by msgeissler** [comment]
The docker-compose file should be seen as an example / or not seen at all by the average end-user of the image.
Seeing how it currently lacks a part in the README (as that is being synced with docker-hub) maybe it should be moved to a CI subfolder, because the travis-build is currently using it.

The alternative would be to switch to volumes instead of filepaths, but then people have to be careful with the commands they run, so they do not accidentally delete their data or keep it forever after a test (so this would need some documentation as well).

**Comment by lucaperret** [comment]
Hi @thebetterjort, have you tried to run the container on Windows ?

**Comment by apihlaja** [comment]
That helped  me to figure out what's the issue with Docker for Windows: https://github.com/docker-library/mongo/issues/243#issuecomment-395025628

It seems NTFS mounts aren't going to work, you have to use something else for MongoDB, named volume being one of the options:

```version: '3'

volumes:
  mongo-data: {}

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - "C:\\Users\\antti\\Code\\strapi-testing\\strapi-app:/usr/src/api/strapi-app"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: always
```

**Comment by lauriejim** [comment]
Can you give us an update please.

**Comment by MatteoGioioso** [comment]
Since there is this problem, how can we migrate the named volume into our production server? 
I was reading here for possible solutions: https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes

Any suggestion? Would you consider to implement it in this repo? I could help if needed

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
