### ISSUE TITLE
Strapi base example image size too big with node_modules

### ISSUE THREAD

**Issue by rams23** [strapi/strapi-docker#223]
The size of the docker image created using the Dockerfile example of the strapi/base is greater than 1GB because it contains all the node_modules required. Is there a way to build the strapi backend and simply run using node a builded file (like a bundle tool output or so)? this will reduce drammatically the image size in production i think.

## Step to reproduce:

- run docker image binding an empty local folder
- copy the Dockerfile of the strapi/base example in the folder
- run docker build

**Comment by alexandrebodin** [comment]
Hello. You can create your own image for sure :) Closing as nothing prevents you from doing what you want :)

**Comment by seanplwong** [comment]
I have the same problem, even with 2 stage build the image is still quite big, 3xx ~ 5xx MB. I found that `strapi-admin` is listing `webpack` as a dependency, if we could avoid installing that, I think we could slim down the image a bit.

**Comment by s-soroosh** [comment]
@alexandrebodin It's true that nothing stops the users to do that, but still would be valuable to explain the best practices here in the **strapi-docker** repository and update the example it has with base images. 
It's a pity to see that following the example outlined in this repository creates such a big image.
Otherwise one can say that the `base` image is too simple to deserve having a file in this repository :)

**Comment by Phhofm** [comment]
Maybe this might help someone to currently reduce the resulting image size so I post it here. My image size with strapi/base was 1.5 GB (it includes some sample data), and my currently produced image size is now 927 MB. When inspecting the new image with

```bash
$ docker run -it image sh
# du -hcs node_modules
```
 the node_modules folder takes 637.7M total of those 927. It would be great if there were a way to reduce this folders size as mentioned by the original poster.
 To reduce the image size, I built on another base layer that was smaller than strapi/base.
Instead of
```yaml
FROM strapi/base
```
I used
```yaml
FROM node:12-alpine
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
```

The full Dockerfile I use for reference:

```yaml
# syntax=docker/dockerfile:1
FROM alpine AS cloner
RUN apk add --no-cache git
RUN git clone https://gitlab.com/rwf-dev-public/timeline.git

#FROM strapi/base - this is the old base layer (1.5G total), replaced by the next two statements (927M total)
FROM node:12-alpine
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
COPY --from=cloner /timeline/backend /
RUN npm install
ENV NODE_ENV production
RUN npm run build
CMD ["npm", "start"]
```

Hope this helps someone :)

**Comment by lphuctai** [comment]
Hi, I want share my Dockerfile, run on stock Strapi v3.6.3.
- Build time about 2'30s on Macbook Pro 2015.
- Image size about ~500MB.

Hope this can help you. ^^
```
FROM node:14-alpine as BUILD_IMAGE

WORKDIR /strapi

# Resolve node_modules for caching
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install --production=true --frozen-lockfile

# Copy all for build and release cache if package.json update
COPY . .
ENV NODE_ENV=production

RUN yarn build

RUN npm prune --production

#------------------------------------------------------------------------------------

FROM node:14-alpine

COPY --from=BUILD_IMAGE /strapi /strapi

WORKDIR /strapi

EXPOSE 1337

ENV NODE_ENV=production
ENV STRAPI_LOG_LEVEL=debug

CMD ["yarn", "start"]

```
