### ISSUE TITLE
3 Critical / 52 High Vulnerabilities in strapi/base image

### ISSUE THREAD

**Issue by Mozart409** [strapi/strapi-docker#318]
![Strapi-docker-security](https://user-images.githubusercontent.com/38767929/136666100-915d30ef-215b-4f1b-87ea-84af96f0ed8c.PNG)

Can those issues be fixed or can I help you guys out?

**Comment by ChristianHeimke** [comment]
The strapi base image uses the base node image as you can see here: https://hub.docker.com/layers/strapi/strapi/3.6.8-alpine/images/sha256-cdaa58079a087af4a623591005a8b8c86ca409b28420af148c2e4d7c5ec9da76?context=explore or here 
https://github.com/strapi/strapi-docker/blob/master/base/Dockerfile 

The vulnerabilities needs to be fixed in the node image and rebuild the strapi image after it. the current build scripts do not support rebuilding an existing tag (and afaik is not wanted by docker because of the uniqueness of a tag/container/image (yes the tag can be overwritten...)).
